//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveWorldWPFClient.OrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetDates", ReplyAction="http://tempuri.org/IOrderService/GetDatesResponse")]
        string GetDates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetDates", ReplyAction="http://tempuri.org/IOrderService/GetDatesResponse")]
        System.Threading.Tasks.Task<string> GetDatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrderLine", ReplyAction="http://tempuri.org/IOrderService/AddOrderLineResponse")]
        void AddOrderLine(int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrderLine", ReplyAction="http://tempuri.org/IOrderService/AddOrderLineResponse")]
        System.Threading.Tasks.Task AddOrderLineAsync(int productId, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : SaveWorldWPFClient.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<SaveWorldWPFClient.OrderServiceReference.IOrderService>, SaveWorldWPFClient.OrderServiceReference.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDates() {
            return base.Channel.GetDates();
        }
        
        public System.Threading.Tasks.Task<string> GetDatesAsync() {
            return base.Channel.GetDatesAsync();
        }
        
        public void AddOrderLine(int productId, int quantity) {
            base.Channel.AddOrderLine(productId, quantity);
        }
        
        public System.Threading.Tasks.Task AddOrderLineAsync(int productId, int quantity) {
            return base.Channel.AddOrderLineAsync(productId, quantity);
        }
    }
}
