//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveTheWorldWebsite.ServiceReferenceDisaster {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisasterB", Namespace="http://schemas.datacontract.org/2004/07/SaveWorldModel")]
    [System.SerializableAttribute()]
    public partial class DisasterB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisasterBankAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisasterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VictimsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisasterBankAccountId {
            get {
                return this.DisasterBankAccountIdField;
            }
            set {
                if ((this.DisasterBankAccountIdField.Equals(value) != true)) {
                    this.DisasterBankAccountIdField = value;
                    this.RaisePropertyChanged("DisasterBankAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisasterId {
            get {
                return this.DisasterIdField;
            }
            set {
                if ((this.DisasterIdField.Equals(value) != true)) {
                    this.DisasterIdField = value;
                    this.RaisePropertyChanged("DisasterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Victims {
            get {
                return this.VictimsField;
            }
            set {
                if ((this.VictimsField.Equals(value) != true)) {
                    this.VictimsField = value;
                    this.RaisePropertyChanged("Victims");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDisaster.IDisasterService")]
    public interface IDisasterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/GetAllDisasters", ReplyAction="http://tempuri.org/IDisasterService/GetAllDisastersResponse")]
        SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB[] GetAllDisasters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/GetAllDisasters", ReplyAction="http://tempuri.org/IDisasterService/GetAllDisastersResponse")]
        System.Threading.Tasks.Task<SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB[]> GetAllDisastersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/GetDisasterByName", ReplyAction="http://tempuri.org/IDisasterService/GetDisasterByNameResponse")]
        SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB GetDisasterByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/GetDisasterByName", ReplyAction="http://tempuri.org/IDisasterService/GetDisasterByNameResponse")]
        System.Threading.Tasks.Task<SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB> GetDisasterByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/UpdateDisaster", ReplyAction="http://tempuri.org/IDisasterService/UpdateDisasterResponse")]
        bool UpdateDisaster(SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB disaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/UpdateDisaster", ReplyAction="http://tempuri.org/IDisasterService/UpdateDisasterResponse")]
        System.Threading.Tasks.Task<bool> UpdateDisasterAsync(SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB disaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/DeleteDisaster", ReplyAction="http://tempuri.org/IDisasterService/DeleteDisasterResponse")]
        void DeleteDisaster(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/DeleteDisaster", ReplyAction="http://tempuri.org/IDisasterService/DeleteDisasterResponse")]
        System.Threading.Tasks.Task DeleteDisasterAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/CheckNameIfExists", ReplyAction="http://tempuri.org/IDisasterService/CheckNameIfExistsResponse")]
        bool CheckNameIfExists(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/CheckNameIfExists", ReplyAction="http://tempuri.org/IDisasterService/CheckNameIfExistsResponse")]
        System.Threading.Tasks.Task<bool> CheckNameIfExistsAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDisasterServiceChannel : SaveTheWorldWebsite.ServiceReferenceDisaster.IDisasterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisasterServiceClient : System.ServiceModel.ClientBase<SaveTheWorldWebsite.ServiceReferenceDisaster.IDisasterService>, SaveTheWorldWebsite.ServiceReferenceDisaster.IDisasterService {
        
        public DisasterServiceClient() {
        }
        
        public DisasterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DisasterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisasterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisasterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB[] GetAllDisasters() {
            return base.Channel.GetAllDisasters();
        }
        
        public System.Threading.Tasks.Task<SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB[]> GetAllDisastersAsync() {
            return base.Channel.GetAllDisastersAsync();
        }
        
        public SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB GetDisasterByName(string name) {
            return base.Channel.GetDisasterByName(name);
        }
        
        public System.Threading.Tasks.Task<SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB> GetDisasterByNameAsync(string name) {
            return base.Channel.GetDisasterByNameAsync(name);
        }
        
        public bool UpdateDisaster(SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB disaster) {
            return base.Channel.UpdateDisaster(disaster);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDisasterAsync(SaveTheWorldWebsite.ServiceReferenceDisaster.DisasterB disaster) {
            return base.Channel.UpdateDisasterAsync(disaster);
        }
        
        public void DeleteDisaster(int id) {
            base.Channel.DeleteDisaster(id);
        }
        
        public System.Threading.Tasks.Task DeleteDisasterAsync(int id) {
            return base.Channel.DeleteDisasterAsync(id);
        }
        
        public bool CheckNameIfExists(string name) {
            return base.Channel.CheckNameIfExists(name);
        }
        
        public System.Threading.Tasks.Task<bool> CheckNameIfExistsAsync(string name) {
            return base.Channel.CheckNameIfExistsAsync(name);
        }
    }
}
