//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveTheWorldDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bankAccount()
        {
            this.auser = new HashSet<auser>();
            this.disaster = new HashSet<disaster>();
        }
    
        public int id { get; set; }
        public int accountNo { get; set; }
        public System.DateTime expiryDate { get; set; }
        public int ccv { get; set; }
        public double amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auser> auser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disaster> disaster { get; set; }
    }
}
