//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveTheWorldDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public int id { get; set; }
        public string name { get; set; }
        public int sortOrder { get; set; }
        public Nullable<int> propertyValuesId { get; set; }
    
        public virtual propertyValues propertyValues { get; set; }
    }
}
