//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveWorldWPFClient.DisasterReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DisasterReferences.IDisasterService")]
    public interface IDisasterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/GetAllDisasters", ReplyAction="http://tempuri.org/IDisasterService/GetAllDisastersResponse")]
        SaveWorldModel.Disaster[] GetAllDisasters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisasterService/GetAllDisasters", ReplyAction="http://tempuri.org/IDisasterService/GetAllDisastersResponse")]
        System.Threading.Tasks.Task<SaveWorldModel.Disaster[]> GetAllDisastersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDisasterServiceChannel : SaveWorldWPFClient.DisasterReferences.IDisasterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisasterServiceClient : System.ServiceModel.ClientBase<SaveWorldWPFClient.DisasterReferences.IDisasterService>, SaveWorldWPFClient.DisasterReferences.IDisasterService {
        
        public DisasterServiceClient() {
        }
        
        public DisasterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DisasterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisasterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisasterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SaveWorldModel.Disaster[] GetAllDisasters() {
            return base.Channel.GetAllDisasters();
        }
        
        public System.Threading.Tasks.Task<SaveWorldModel.Disaster[]> GetAllDisastersAsync() {
            return base.Channel.GetAllDisastersAsync();
        }
    }
}
